[package]
name = "ivadsiuls/genRojoProject"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
dataservice = "leifstout/dataservice@0.3.1"
networker = "leifstout/networker@0.3.0"
vide = "centau/vide@0.3.1"
signal = "sleitnick/signal@2.0.3"
promise = "evaera/promise@4.0.0"
maid = "nightcycle/maid@2.2.2"
conch = "alicesaidhi/conch@0.3.1"
sift = "csqrl/sift@0.0.11"

[server-dependencies]
